### PR TITLE
Add dark mode

### LINKED ISSUE #4: Dark mode
Tailwind CSS is utilized in this project. Changes are needed in:
* [Theme configuration](https://github.com/HydPy/pyconfhyd2025/blob/main/tailwind.config.js)
* [Components](https://github.com/HydPy/pyconfhyd2025/tree/main/src/components)

For reference, see [Tailwind CSS Dark Mode documentation](https://tailwindcss.com/docs/dark-mode).

### PR DESCRIPTION
**Pull request by shivkatira**
**Summary:**

1. public/images/monumentsSketch.svg [Switches bg from white to transparent, Changes outline color from #018b87 to #016e6b]
2. src/app/layout.js [Sets bg color for dark mode]
3. src/components/Header.jsx [Adds toggle theme icon, Changes for dark mode]
4. src/components/Hero.jsx [Changes color for announcement text]
5. src/components/Icon.jsx [Declares toggle theme icon]
6. src/components/ThemeToggle.jsx [Adds code for toggle theme]
7. tailwind.config.js [Adds color palette for dark mode]

**Issue Link:**

fix #4 

**PR Checks:**

- [ ] Code is properly formatted (executed `make pre-push` command).
- [ ] No ESLint warnings (verified with `make pre-push` command).
- [ ] UI Changes are responsive (checked in the responsive view).
- [ ] Performance is maintained (Lighthouse report reviewed).
- [ ] User experience (UX) considerations are met.
- [ ] Accessibility is supported (validated with accessibility tools).

### CODE REVIEW

**Review by RajatRajdeep — APPROVED** [review]
There is a slight flicker when the dark theme is selected by default, but it is not a blocker for this PR. Other than that, the changes look good to me.

Thank you @shivkatira for your contributions.

**Comment by bhansa** [comment]
Flicker can be fixed, https://www.youtube.com/watch?v=7zqI4qMDdg8

**Comment by shivkatira** [comment]
@bhansa I have very limited availability this month, it would be great if anyone else can take it up. Thnx.

**Comment by bhansa** [comment]
Sure, no problem @shivkatira I'll raise a change PR this week.

**Pull request merged**
